### PR TITLE
Fix issue where request panel doesn't update

### LINKED ISSUE #13: Requests made by the devtools panel don't always return
## About
Due to the way subscriptions work, the devtools panel is unable to determine whether a request has been completed or not.

### PR DESCRIPTION
**Pull request by andyrichardson**
Fix #13

### CODE REVIEW

File: src/exchange.ts [hunk 1]
```diff
@@ -32,6 +30,7 @@ export const devtoolsExchange: Exchange = ({ client, forward }) => {
 
   // Listen for messages from content script
   window.addEventListener(DevtoolsExchangeIncomingEventType, event => {
+    console.log(event);
```
Comment (JoviDeCroock) [inline src/exchange.ts]: Redundant log

Comment (andyrichardson) [reply src/exchange.ts]: Yeah hold of on this for a short mo - needs some tweaks
